// <auto-generated />
namespace MyBlog.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_database_17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_database_17));
        
        string IMigrationMetadata.Id
        {
            get { return "202108280525321_update_database_17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
